# 应用服务 WEB 访问端口
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  ssl:
    enabled: false
  servlet:
    context-path: /card
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
# 数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/card?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# Python 脚本位置
logging:
  level:
    com.hust.card: info

